Repository NVIDIA/libcudacxx, pull requests merged in 2021-07, with the labels that each got.

#177 Make <nv/target> usable in C and C++98 compilations
  include/nv/target
Labels: P0: must have, bug: functional

#187 Several fixes for Clang 12 and GCC 11
  .upstream-tests/test/std/utilities/tuple/tuple.tuple/tuple.cnstr/deduct.pass.cpp
  include/cuda/std/detail/__config
  libcxx/include/__config
Labels: bug: functional

#189 Fix upstream test warnings with /s/diag_suppress/nv_diag_suppress/
  .upstream-tests/test/cuda/barrier_native_handle.pass.cpp
  .upstream-tests/test/cuda/pipeline_arrive_on.pass.cpp
  .upstream-tests/test/cuda/pipeline_arrive_on_abi_v2.pass.cpp
  .upstream-tests/test/libcxx/libcpp_alignof.pass.cpp
  .upstream-tests/test/std/language.support/support.types/max_align_t.pass.cpp
  .upstream-tests/test/std/utilities/function.objects/func.invoke/invoke.pass.cpp
  .upstream-tests/test/std/utilities/function.objects/func.not_fn/not_fn.pass.cpp
  .upstream-tests/test/std/utilities/meta/meta.unary/meta.unary.cat/floating_point.pass.cpp
  .upstream-tests/test/std/utilities/meta/meta.unary/meta.unary.cat/is_floating_point.pass.cpp
  .upstream-tests/test/std/utilities/meta/meta.unary/meta.unary.comp/floating_point.pass.cpp
  .upstream-tests/test/std/utilities/meta/meta.unary/meta.unary.comp/is_fundamental.pass.cpp
  .upstream-tests/test/std/utilities/meta/meta.unary/meta.unary.prop/is_constructible.pass.cpp
  .upstream-tests/test/std/utilities/time/date.time/ctime.pass.cpp
  .upstream-tests/test/std/utilities/time/time.duration/time.duration.arithmetic/op_+.pass.cpp
  .upstream-tests/test/std/utilities/time/time.duration/time.duration.arithmetic/op_-.pass.cpp
Labels: P0: must have, only: tests

#172 Bugfix/abi breaking changes
  .upstream-tests/test/cuda/pipeline_arrive_on.pass.cpp
  .upstream-tests/test/std/numerics/complex.number/complex/abi_latest.pass.cpp
  .upstream-tests/test/std/numerics/complex.number/complex/abi_v3.pass.cpp
  .upstream-tests/test/std/utilities/time/time.duration/time.duration.literals/literals.abiv3.pass.cpp
  include/cuda/std/detail/__config
  libcxx/include/chrono
  libcxx/include/complex
Labels: testing: internal ci passed

#111 Add parity waiting
  .upstream-tests/test/heterogeneous/barrier_parity.pass.cpp
  include/cuda/std/barrier
  libcxx/include/barrier
Labels: P2: nice to have, enhancement, testing: internal ci passed
