Repository NVIDIA/libcudacxx, pull requests merged in 2022-02, with the labels that each got.

#241 Use decimal notation for version number.
  include/cuda/std/detail/__config
Labels: enhancement, testing: internal ci passed

#234 Fix host only compilation of <cuda/std/cmath>
  include/cuda/std/cmath
  include/cuda/std/detail/libcxx/include/cmath
Labels: testing: internal ci passed

#240 print output to JSON_OUTPUT_PATH
  .upstream-tests/utils/nvidia/linux/docker/run_docker_image.bash
  .upstream-tests/utils/nvidia/linux/perform_tests.bash
Labels: testing: internal ci passed, nvbug

#237 Backports to C++11 of <bit>
  .upstream-tests/test/std/numerics/bit/bit.endian/endian.pass.cpp
  .upstream-tests/test/std/numerics/bit/bit.pow.two/bit_ceil.fail.cpp
  .upstream-tests/test/std/numerics/bit/bit.pow.two/bit_ceil.pass.cpp
  .upstream-tests/test/std/numerics/bit/bit.pow.two/bit_floor.pass.cpp
  .upstream-tests/test/std/numerics/bit/bit.pow.two/bit_width.pass.cpp
  .upstream-tests/test/std/numerics/bit/bit.pow.two/has_single_bit.pass.cpp
  .upstream-tests/test/std/numerics/bit/bitops.count/countl_one.pass.cpp
  .upstream-tests/test/std/numerics/bit/bitops.count/countl_zero.pass.cpp
  .upstream-tests/test/std/numerics/bit/bitops.count/countr_one.pass.cpp
  .upstream-tests/test/std/numerics/bit/bitops.count/countr_zero.pass.cpp
  .upstream-tests/test/std/numerics/bit/bitops.count/popcount.pass.cpp
  .upstream-tests/test/std/numerics/bit/bitops.rot/rotl.pass.cpp
  .upstream-tests/test/std/numerics/bit/bitops.rot/rotr.pass.cpp
  .upstream-tests/test/std/numerics/bit/invocable.pass.cpp
  .upstream-tests/test/std/numerics/bit/nothing_to_do.pass.cpp
  include/cuda/std/bit
  include/cuda/std/detail/__config
  include/cuda/std/detail/libcxx/include/__config
  include/cuda/std/detail/libcxx/include/bit
  libcxx/test/libcxx/numerics/bit.ops.pass.cpp
  libcxx/test/std/numerics/bit/bit.pow.two/bit_ceil.fail.cpp
  libcxx/test/std/numerics/bit/bit.pow.two/bit_ceil.pass.cpp
  libcxx/test/std/numerics/bit/bit.pow.two/bit_floor.pass.cpp
  libcxx/test/std/numerics/bit/bit.pow.two/bit_width.pass.cpp
  libcxx/test/std/numerics/bit/bit.pow.two/has_single_bit.pass.cpp
Labels: testing: internal ci passed
